# WORK IN PROGRESS
version: '3.8'
services:
  ollama-tg:
    build: .
    container_name: ollama-tg
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ollama-tg:/code/ # Mounting a volume for SQLite database
volumes:
  ollama-tg:
